import React, { useState, useEffect } from "react";
import {
  query$,
  mutation$,
  execute,
  setGraphQLExecutor,
} from "@ptdgrp/typedgql";
import { executeGraphQL } from "./executor";

// Intercept queries for testing display
let currentQueryRequest = "";
let currentQueryVariables: any = {};

setGraphQLExecutor(async (request, variables) => {
  currentQueryRequest = request;
  currentQueryVariables = variables || {};
  return executeGraphQL(request, variables);
});

export default function App() {
  const [logs, setLogs] = useState<
    { title: string; query: string; variables: any; result: any }[]
  >([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const runTest = async () => {
    setLoading(true);
    setError(null);
    setLogs([]);
    const testLogs: any[] = [];

    try {
      // 1. Fetch Posts
      const postsQuery = query$.posts((post) =>
        post.id.title.publishedAt
          .author((author) => author.id.name)
          .comments((comment) =>
            comment.id.body.createdAt.author((a) => a.id.name),
          )
          .tags((tag) => tag.id.name),
      );
      const data1 = await execute(postsQuery);
      testLogs.push({
        title: "Fetch Posts",
        query: currentQueryRequest,
        variables: currentQueryVariables,
        result: data1,
      });

      // 2. Fetch Single Post
      const postQuery = query$.post((post) =>
        post.id.title.content
          .author((author) => author.id.name)
          .tags((tag) => tag.name),
      );
      const data2 = await execute(postQuery, { variables: { id: "p2" } });
      testLogs.push({
        title: 'Fetch Post "p2"',
        query: currentQueryRequest,
        variables: currentQueryVariables,
        result: data2,
      });

      // 3. Create Post
      const createPostMut = mutation$.createPost((post) =>
        post.id.title.publishedAt.author((a) => a.name),
      );
      const createInput = {
        title: "Introduction to typedgql",
        content: "typedgql provides end-to-end type safety for GraphQL...",
        authorId: "a1",
        tagIds: ["t1", "t2"],
      };
      const data3 = await execute(createPostMut, {
        variables: { input: createInput },
      });
      testLogs.push({
        title: "Create Post",
        query: currentQueryRequest,
        variables: currentQueryVariables,
        result: data3,
      });

      // 4. Add Comment
      const addCommentMut = mutation$.addComment((comment) =>
        comment.id.body.createdAt.author((a) => a.id.name),
      );
      const data4 = await execute(addCommentMut, {
        variables: {
          input: {
            postId: "p1",
            body: "This is exactly what I was looking for!",
            authorId: "a2",
          },
        },
      });
      testLogs.push({
        title: "Add Comment to p1",
        query: currentQueryRequest,
        variables: currentQueryVariables,
        result: data4,
      });

      setLogs(testLogs);
    } catch (err: any) {
      console.error(err);
      setError(err.message || String(err));
      // still show what succeeded
      setLogs(testLogs);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    runTest();
  }, []);

  return (
    <div
      style={{
        padding: "2rem",
        fontFamily: "sans-serif",
        maxWidth: "1200px",
        margin: "0 auto",
      }}
    >
      <h1 style={{ borderBottom: "2px solid #333", paddingBottom: "10px" }}>
        TypedGQL Blog Example Workflow
      </h1>
      <p style={{ color: "#666" }}>
        This page runs the standard GraphQL flow using the code generated by
        typedgql to ensure queries and mutations yield the expected GraphQL
        documents and get resolved correctly by our in-memory executor.
      </p>
      <button
        onClick={runTest}
        disabled={loading}
        style={{
          padding: "10px 20px",
          marginBottom: "20px",
          cursor: loading ? "not-allowed" : "pointer",
          backgroundColor: "#007acc",
          color: "white",
          border: "none",
          borderRadius: "4px",
          fontWeight: "bold",
        }}
      >
        {loading ? "Running..." : "Run Tests"}
      </button>

      {error && (
        <div
          style={{
            padding: "15px",
            backgroundColor: "#ffebee",
            color: "#c62828",
            border: "1px solid #ef9a9a",
            borderRadius: "4px",
            marginBottom: "20px",
          }}
        >
          <strong>Error during execution: </strong>
          {error}
        </div>
      )}

      {logs.map((log, index) => (
        <div
          key={index}
          style={{
            marginBottom: "2rem",
            border: "1px solid #e0e0e0",
            borderRadius: "8px",
            overflow: "hidden",
            boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
          }}
        >
          <div
            style={{
              backgroundColor: "#f5f5f5",
              padding: "12px 15px",
              borderBottom: "1px solid #e0e0e0",
            }}
          >
            <h2 style={{ margin: 0, fontSize: "1.2rem", color: "#333" }}>
              {log.title}
            </h2>
          </div>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              margin: 0,
              flexDirection: "row",
            }}
          >
            <div
              style={{
                flex: "1 1 50%",
                padding: "15px",
                borderRight: "1px solid #e0e0e0",
                boxSizing: "border-box",
                minWidth: "300px",
              }}
            >
              <h3 style={{ margin: "0 0 10px 0", fontSize: "1rem" }}>
                Generated GraphQL Document
              </h3>
              <pre
                style={{
                  backgroundColor: "#2d2d2d",
                  color: "#f8f8f2",
                  padding: "15px",
                  borderRadius: "6px",
                  overflowX: "auto",
                  fontSize: "14px",
                  lineHeight: "1.4",
                }}
              >
                {log.query}
              </pre>
              {Object.keys(log.variables).length > 0 && (
                <>
                  <h4 style={{ margin: "15px 0 10px 0", fontSize: "1rem" }}>
                    Variables
                  </h4>
                  <pre
                    style={{
                      backgroundColor: "#2d2d2d",
                      color: "#f8f8f2",
                      padding: "15px",
                      borderRadius: "6px",
                      overflowX: "auto",
                      fontSize: "14px",
                      lineHeight: "1.4",
                    }}
                  >
                    {JSON.stringify(log.variables, null, 2)}
                  </pre>
                </>
              )}
            </div>
            <div
              style={{
                flex: "1 1 50%",
                padding: "15px",
                boxSizing: "border-box",
                minWidth: "300px",
              }}
            >
              <h3 style={{ margin: "0 0 10px 0", fontSize: "1rem" }}>
                Execution Result
              </h3>
              <pre
                style={{
                  backgroundColor: "#f8f9fa",
                  padding: "15px",
                  borderRadius: "6px",
                  overflowX: "auto",
                  fontSize: "14px",
                  lineHeight: "1.4",
                  border: "1px solid #eee",
                  height: "100%",
                  boxSizing: "border-box",
                }}
              >
                {JSON.stringify(log.result, null, 2)}
              </pre>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
